name: CI/CD for React Todo

on:
  push:
    branches:
      - main  # Trigger action only on main branch pushes

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd todo  # If your app is in a subdirectory like 'todo'
          npm install

      - name: Build Project
        run: |
          cd todo  # If your app is in a subdirectory like 'todo'
          npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./todo/build  # Path to the build folder

  # Deploy Job
  deploy:
    needs: build  # Ensures this job runs only after the build job completes
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./todo/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY }}  # Access token to push to GitHub Pages
          publish_dir: ./todo/build  # Directory containing build files
